# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

container:
  
  replicaCount: 3

  image:
    repository: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/staging/api
    tag: latest
    pullPolicy: Always
  
  port: 8080

  resources:
    limits:
      memory: "512Mi"
      cpu: "1"
    requests:
      memory: "256Mi"
      cpu: "0.5"

  probe:
    enabled: false
    path: /
    livenessTimeOut: 5
    readinessDelay:  5

service:
  type: ClusterIP
  port: 80
  httpsPort: 443

ingress:
  enabled: true
  annotations: {}
  host: <DNS_ROOT_NAME>
  paths: /

configmap: []

secret:
  enabled: false
  external:
    - name: staging/api
      keys: DATABASE_USER
    - name: staging/api
      keys: DATABASE_PASSWORD
