# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

container:
  
  replicaCount: 3

  image:
    repository: 869690475570.dkr.ecr.eu-west-1.amazonaws.com/prod/api
    tag: latest
    pullPolicy: Always
  
  port: 3000

  resources:
    limits:
      memory: "512Mi"
      cpu: "1"
    requests:
      memory: "256Mi"
      cpu: "0.5"

  probe:
    enabled: false
    path: /
    livenessTimeOut: 5
    readinessDelay:  5

service:
  type: ClusterIP
  port: 80
  httpsPort: 443

ingress:
  enabled: true
  annotations: {}
  host: api.app-prod.env.remilab.forge-demo.fr
  paths: /

configmap: []

secret:
  enabled: true
  external:
    - name: env-app-prod-pgsql-db
      keys: password
